export const API_URL = 'https://api.unsplash.com';
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token';
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize';
export const ACCESS_KEY = 'Uhrr5NtSAEqp8ILiMMG8eFBSwKywg0cjR9fhauP0RS0';
export const SECRET_KEY = '8lFkQst-AC2jRTqGYPR0_ESU2Ax79DqdUsTxPGScswQ';
export const REDIRECT_URI = 'https://rootdiv.github.io/online-gallery/';
export const RESPONSE_TYPE = 'code';
export const SCOPE = 'public read_user read_photos write_likes';
